Repository padiix/SignalRChatTest, pull requests merged in 2020-12, with the labels that each got.

#2 Added Active Users
  SginalRChatTest/Hubs/ChatHub.cs
  SginalRChatTest/Model/UsersConnections.cs
  SginalRChatTest/Pages/Index.cshtml
  SginalRChatTest/wwwroot/js/chat.js
Labels: enhancement

#3 Centered context of the page
  SginalRChatTest/Pages/Index.cshtml
  SginalRChatTest/wwwroot/css/chat.css
  SginalRChatTest/wwwroot/js/activeUserPanel.js
Labels: bug fix

#4 Release 2.0
  SginalRChatTest/Hubs/ChatHub.cs
  SginalRChatTest/Model/UsersConnections.cs
  SginalRChatTest/Pages/Index.cshtml
  SginalRChatTest/wwwroot/css/chat.css
  SginalRChatTest/wwwroot/js/activeUserPanel.js
  SginalRChatTest/wwwroot/js/chat.js
Labels: release
